[workspace]
resolver = "2"
members = ["macros", "pipewire", "spa", "tools"]
default-members = ["macros", "pipewire", "spa", "tools"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
pipewire-native-macros = { path = "macros", version = "0.1" }
pipewire-native-spa = { path = "spa", version = "0.1" }
pipewire-native = { path = "pipewire", version = "0.1" }
pipewire-native-tools = { path = "tools", version = "0.1" }
