[package]
name = "pipewire-native-macros"
description = "Helper macros for the pipewire-native crate"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
syn = { version = "2.0", features = ["extra-traits", "full"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
pipewire-native-spa = { path = "../spa" }

[lib]
proc-macro = true
