[package]
name = "pipewire-native-macros"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
syn = { version = "*", features = ["extra-traits", "full"] }
quote = "*"
proc-macro2 = "*"

[dev-dependencies]
pipewire-native-spa.workspace = true

[lib]
proc-macro = true
