[package]
name = "pipewire-native-spa"
version.workspace = true
edition.workspace = true

[dependencies]
bitflags.workspace = true
libc.workspace = true
libloading = "0.8.6"
num = "0.4.3"
pipewire-native-macros.workspace = true

[dev-dependencies]
# For tests
libspa = "0.8.0"

[build-dependencies]
cc = "1.2.22"
